#
# Autogenerated by Thrift Compiler (0.9.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException

from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None


class KeyValueStatus:
  OK = 1
  ERROR = 2

  _VALUES_TO_NAMES = {
    1: "OK",
    2: "ERROR",
  }

  _NAMES_TO_VALUES = {
    "OK": 1,
    "ERROR": 2,
  }

class ChordStatus:
  OK = 1
  ERROR = 2

  _VALUES_TO_NAMES = {
    1: "OK",
    2: "ERROR",
  }

  _NAMES_TO_VALUES = {
    "OK": 1,
    "ERROR": 2,
  }

